# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d5bac471676963d08ff7b8c361bc30939aad8b1b041d88b5c1988342ae174540d1f01f253422648f4b666c7ead7ca532ca225b2f146cc5eb77c23efd6084150c

test:
  secret_key_base: 02dd2cd991d048ea1f0d9e0734df1fa04a33f273356eaa4754492777847a4e7aec74201b9871c0983497f926fabf0abd5cb0ab723fb061ea2e9fb6df6c511be3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
